# Generated by Django 5.0.6 on 2024-06-27 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-publishDate',), 'verbose_name': '学校建筑', 'verbose_name_plural': '学校建筑'},
        ),
        migrations.AlterModelOptions(
            name='productimg',
            options={'verbose_name': '展品图片', 'verbose_name_plural': '展品图片'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='展品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='资金投入'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('艺术博物馆', '艺术博物馆'), ('科学博物馆', '科学博物馆'), ('新清华学堂', '新清华学堂')], max_length=50, verbose_name='建筑类型'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, verbose_name='展品标题'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Product/', verbose_name='展品图片'),
        ),
        migrations.AlterField(
            model_name='productimg',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImgs', to='productsApp.product', verbose_name='学校建筑'),
        ),
    ]
