# Generated by Django 4.2.11 on 2024-06-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0004_auto_20191003_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2024-06-13', max_length=20, verbose_name='出生日期'),
        ),
    ]
