# Generated by Django 5.0.6 on 2024-06-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0006_alter_resume_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2024-06-27', max_length=20, verbose_name='出生日期'),
        ),
    ]
