# Generated by Django 5.0.6 on 2024-06-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_mynew_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynew',
            name='newType',
            field=models.CharField(choices=[('综合时讯', '综合时讯'), ('交流合作', '交流合作'), ('最新动态', '最新动态')], max_length=50, verbose_name='新闻类型'),
        ),
    ]
